%ifndef Includes_Hardware_Timer_I
%define Includes_Hardware_Timer_I

;
; (C) Copyright 1999 Mindkiller Systems, inc.
;     All rights reserved.
;
;     Includes release V1.0.0
;
;     Timer.I V1.0.0
;
;     Timer hardware includes.
;

;-   -  - -- ---=--=-==-===-====-==============-====-===-==-=--=--- -- -  -   -

TIMER_CTRL	EQU	0x43	; I/O for control
TIMER_COUNT0	EQU	0x40	; I/O for counter 0
TIMER_COUNT1	EQU	0x41	; I/O for counter 1
TIMER_COUNT2	EQU	0x42	; I/O for counter 2


;-   -  - -- ---=--=-==-===-====-==============-====-===-==-=--=--- -- -  -   -

%endif
