%ifndef Includes_LVO_Font_I
%define Includes_LVO_Font_I

;
; (C) Copyright 1999-2001 Mindkiller Systems, inc.
;     All rights reserved.
;
;     Includes release V1.0.0
;
;     Font.I V1.0.0
;
;     Library Vector Offsets for Font library
;

	LIBINIT
	LIBDEF	LVOOpenFont
	LIBDEF	LVOCloseFont
	LIBDEF	LVORenderFont

;-   -  - -- ---=--=-==-===-====-==============-====-===-==-=--=--- -- -  -   -
%endif

