%ifndef Includes_LVO_Graphics_I
%define Includes_LVO_Graphics_I

;
; (C) Copyright 1999-2002 Mindkiller Systems, inc.
;     All rights reserved.
;
;     Includes release V1.0.0
;
;     Graphics.I V1.0.0
;
;     Library Vector Offsets for Graphics library
;

	LIBINIT
	LIBDEF	LVODrawLine
	LIBDEF	LVOObtainPen
	LIBDEF	LVOPolyDraw
	LIBDEF	LVORectFill
	LIBDEF	LVOPutPixel
	LIBDEF	LVODrawBevel
	LIBDEF	LVOBltBitmap
	LIBDEF	LVOSetPalette

;-   -  - -- ---=--=-==-===-====-==============-====-===-==-=--=--- -- -  -   -
%endif

