%ifndef Includes_LVO_InputHandler_I
%define Includes_LVO_InputHandler_I

;
; (C) Copyright 1999-2000 Mindkiller Systems, inc.
;     All rights reserved.
;
;     Includes release V1.0.0
;
;     InputHandler.I V1.0.0
;
;     Library Vector Offsets for Input-Handler library
;

	LIBINIT
	LIBDEF	LVOGetMouseCoords
	LIBDEF	LVOGetMouseState
	LIBDEF	LVORefreshMouse

;-   -  - -- ---=--=-==-===-====-=====-====-===-==-=--=--- -- -  -   -
%endif
