%ifndef Includes_LVO_UserInterface_I
%define Includes_LVO_UserInterface_I

;
; (C) Copyright 1999-2001 Mindkiller Systems, inc.
;     All rights reserved.
;
;     Includes release V1.0.0
;
;     UserInterface.I V1.0.0
;
;     Library Vector Offsets for UserInterface library
;

	LIBINIT
	LIBDEF	LVOCloseWindow
	LIBDEF	LVOOpenWindow
	LIBDEF	LVOCreateObjectList
	LIBDEF	LVODisposeObjectList
	LIBDEF	LVOLayoutObjectList
	LIBDEF	LVOCreateObject
	LIBDEF	LVODisposeObject
	LIBDEF	LVOFindScreen
	LIBDEF	LVOUserMethod
	LIBDEF	LVORegisterClass
	LIBDEF	LVOUnregisterClass
	LIBDEF	LVODoMethod

;-   -  - -- ---=--=-==-===-====-=====-====-===-==-=--=--- -- -  -   -
%endif
