%ifndef Includes_LVO_Utility_I
%define Includes_LVO_Utility_I

;
; (C) Copyright 1999-2001 Mindkiller Systems, inc.
;     All rights reserved.
;
;     Includes release V1.0.0
;
;     Utility.I V1.0.0
;
;     Library Vector Offsets for Utility library
;

	LIBINIT
	LIBDEF	LVOStrCmp
	LIBDEF	LVOStriCmp
	LIBDEF	LVOStrLen
	LIBDEF	LVOGetTagData
	LIBDEF	LVOHex2Ascii
	LIBDEF	LVOAscii2Hex
	LIBDEF	LVOCloneTaglist
	LIBDEF	LVOFreeTaglist
	LIBDEF	LVOFindName
	LIBDEF	LVOToLower
	LIBDEF	LVOToUpper
	LIBDEF	LVOSprintf
	LIBDEF	LVOAddNodeSorted
	LIBDEF	LVOSetTagData
	LIBDEF	LVOFindTag
	LIBDEF	LVOFetchTags
	LIBDEF	LVOAddHead
	LIBDEF	LVOAddTail
	LIBDEF	LVOInitList
	LIBDEF	LVOInsertNode
	LIBDEF	LVORemove
	LIBDEF	LVORemoveHead
	LIBDEF	LVORemoveTail


;-   -  - -- ---=--=-==-===-====-==============-====-===-==-=--=--- -- -  -   -
%endif

